---
- hosts: 172.31.13.227
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present
    tags: mygit
  - name: install wget
    apt:
     name: wget
     statea: present
    tags: mywget
  - name: install tree
    apt:
     name: tree
     state: present
    tags: mytree